### ISSUE TITLE
Cross-platform problem

### ISSUE THREAD

**Issue by AlphaNecron** [Visafe/VisafeWindows#2]
Why must you split the program into multiple repositories? You just need 2 repositories. One for Mobile, using either Flutter or React Native, and one for Desktop, using either Avalonia, Uno, Electron or other frameworks. Why making it complicated when you can find a better solution?

**Comment by tranvietha2809** [comment]
@AlphaNecron I'm not a contributor, but I can shed some light on the mobile sides.

Both React Native and Flutter are pride for their UI flexibility across platforms. However, with use cases that are not out-of-the-box like this app, you ended up having to write a lot of native code, on top of your Dart/JS codes and platform api/ bridges. Even more so, this app isn't UI-centric at all, which really diminished whatever few pros cross platform framework might bring about in this case.

That said, I do believe that the real reason is that there weren't any Flutter/React Native repositories they could clone.

**Comment by AlphaNecron** [comment]
Then why don't they try making one from scratch?

**Comment by Long-FA** [comment]
> Then why don't they try making one from scratch?

Spoiler alert: They can't.

**Comment by VisafeTeam** [comment]
Hi @AlphaNecron @Long-FA, we find building Windows service using C# is much more efficient and easier than doing it with other programming languages, that's the reason why.

**Comment by AlphaNecron** [comment]
Just use Electron or other cross-platform frameworks for the frontend, and use C# for the backend.

**Comment by VisafeTeam** [comment]
Using 2 different programming languages in a single application may result in incompatibility. Moreover, devices using older versions of Windows such as Windows 7 may face problems when using newer programming languages.

**Comment by AlphaNecron** [comment]
OK.
